# generate certificate revocation list
#
#
---
- name: Compare existing certs against 'clients' variable
  import_tasks: common.yml
  when: openvpn_sync_certs

- name: remove client config
  file:
    path: "{{ openvpn_ovpn_dir }}/{{item}}-{{ansible_hostname}}.ovpn"
    state: absent
    force: yes
  with_items:
    - '{{ openvpn_revoke_these_certs }}'
    - '{{ additional_certs_to_revoke.stdout_lines }}'

- name: revoke certificates
  command: sh revoke.sh {{ item }}.crt
  args:
    chdir: "{{ openvpn_key_dir }}"
  with_items:
    - '{{ openvpn_revoke_these_certs }}'
    - '{{ additional_certs_to_revoke.stdout_lines }}'

- name: remove client key
  file:
    path: "{{ openvpn_key_dir }}/{{ item }}.key"
    state: absent
    force: yes
  with_items:
    - '{{ openvpn_revoke_these_certs }}'
    - '{{ additional_certs_to_revoke.stdout_lines }}'

- name: remove client csr
  file:
    path: "{{ openvpn_key_dir }}/{{ item }}.csr"
    state: absent
    force: yes
  with_items:
    - '{{ openvpn_revoke_these_certs }}'
    - '{{ additional_certs_to_revoke.stdout_lines }}'
